column_width = 220
indent_type = "Spaces"
indent_width = 2
line_endings = "Unix"
quote_style = "AutoPreferSingle"
call_parentheses = "Input"
syntax = "Lua52"
collapse_simple_statement = "Always"
no_call_parentheses = false

[sort_requires]
enabled = false
